// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yskuyjkdlucvooxvvhwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlza3V5amtkbHVjdm9veHZ2aHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMTg4NzgsImV4cCI6MjA1MDU5NDg3OH0.7RPygZT3u2fSMcoxhAf7JpSOD_Vgy-NsT7qlGAedGmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);